### ISSUE TITLE
seasonality_reg not possible for sub-daily data.

### ISSUE THREAD

**Issue by Lejboelle** [ourownstory/neural_prophet#1228]
**To Reproduce**

1. Generate data with 15 min. intervals (let's call this **df**)
2. Initialize neuralprophet model, e.g.:
```
m = NeuralProphet(yearly_seasonality=16,
    weekly_seasonality=8,
    daily_seasonality=False,
    seasonality_reg=1)
```
3. Run m.fit(df=df, freq="15min")

**Expected behavior**

Model should begin to fit data.

**What actually happens**

Getting an error: ```AttributeError: 'TimeNet' object has no attribute 'season_params'```

Full log:
```
AttributeError                            Traceback (most recent call last)
Cell In[133], line 17
---> 17 metrics = m.fit(df_train, freq="15min")

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/neuralprophet/forecaster.py:866, in NeuralProphet.fit(self, df, freq, validation_df, epochs, batch_size, learning_rate, early_stopping, minimal, metrics, progress, checkpointing, continue_training, num_workers)
    864 # Training
    865 if validation_df is None:
--> 866     metrics_df = self._train(
    867         df,
    868         progress_bar_enabled=bool(progress),
    869         metrics_enabled=bool(self.metrics),
    870         checkpointing_enabled=checkpointing,
    871         continue_training=continue_training,
    872         num_workers=num_workers,
    873     )
    874 else:
    875     df_val, _, _, _ = df_utils.prep_or_copy_df(validation_df)

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/neuralprophet/forecaster.py:2754, in NeuralProphet._train(self, df, df_val, progress_bar_enabled, metrics_enabled, checkpointing_enabled, continue_training, num_workers)
   2752 self.config_train.set_lr_finder_args(dataset_size=dataset_size, num_batches=len(train_loader))
   2753 # Find suitable learning rate
-> 2754 lr_finder = self.trainer.tuner.lr_find(
   2755     self.model,
   2756     train_dataloaders=train_loader,
   2757     **self.config_train.lr_finder_args,
   2758 )
   2759 assert lr_finder is not None
   2760 # Estimate the optimat learning rate from the loss curve

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/tuner/tuning.py:267, in Tuner.lr_find(self, model, train_dataloaders, val_dataloaders, dataloaders, datamodule, method, min_lr, max_lr, num_training, mode, early_stop_threshold, update_attr)
    264 lr_finder_callback._early_exit = True
    265 self.trainer.callbacks = [lr_finder_callback] + self.trainer.callbacks
--> 267 self.trainer.fit(model, train_dataloaders, val_dataloaders, datamodule)
    269 self.trainer.callbacks = [cb for cb in self.trainer.callbacks if cb is not lr_finder_callback]
    271 self.trainer.auto_lr_find = False

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:608, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    606 model = self._maybe_unwrap_optimized(model)
    607 self.strategy._lightning_module = model
--> 608 call._call_and_handle_interrupt(
    609     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    610 )

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py:38, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     36         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
     37     else:
---> 38         return trainer_fn(*args, **kwargs)
     40 except _TunerExitException:
     41     trainer._call_teardown_hook()

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:650, in Trainer._fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    643 ckpt_path = ckpt_path or self.resume_from_checkpoint
    644 self._ckpt_path = self._checkpoint_connector._set_ckpt_path(
    645     self.state.fn,
    646     ckpt_path,  # type: ignore[arg-type]
    647     model_provided=True,
    648     model_connected=self.lightning_module is not None,
    649 )
--> 650 self._run(model, ckpt_path=self.ckpt_path)
    652 assert self.state.stopped
    653 self.training = False

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:1097, in Trainer._run(self, model, ckpt_path)
   1095 # hook
   1096 if self.state.fn == TrainerFn.FITTING:
-> 1097     self._call_callback_hooks("on_fit_start")
   1098     self._call_lightning_module_hook("on_fit_start")
   1100 self._log_hyperparams()

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:1394, in Trainer._call_callback_hooks(self, hook_name, *args, **kwargs)
   1392     if callable(fn):
   1393         with self.profiler.profile(f"[Callback]{callback.state_key}.{hook_name}"):
-> 1394             fn(self, self.lightning_module, *args, **kwargs)
   1396 if pl_module:
   1397     # restore current_fx when nested context
   1398     pl_module._current_fx_name = prev_fx_name

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/callbacks/lr_finder.py:122, in LearningRateFinder.on_fit_start(self, trainer, pl_module)
    121 def on_fit_start(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
--> 122     self.lr_find(trainer, pl_module)

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/callbacks/lr_finder.py:107, in LearningRateFinder.lr_find(self, trainer, pl_module)
    105 def lr_find(self, trainer: "pl.Trainer", pl_module: "pl.LightningModule") -> None:
    106     with isolate_rng():
--> 107         self.optimal_lr = lr_find(
    108             trainer,
    109             pl_module,
    110             min_lr=self._min_lr,
    111             max_lr=self._max_lr,
    112             num_training=self._num_training_steps,
    113             mode=self._mode,
    114             early_stop_threshold=self._early_stop_threshold,
    115             update_attr=self._update_attr,
    116         )
    118     if self._early_exit:
    119         raise _TunerExitException()

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/tuner/lr_finder.py:247, in lr_find(trainer, model, min_lr, max_lr, num_training, mode, early_stop_threshold, update_attr)
    244 lr_finder._exchange_scheduler(trainer)
    246 # Fit, lr & loss logged in callback
--> 247 _try_loop_run(trainer, params)
    249 # Prompt if we stopped early
    250 if trainer.global_step != num_training + start_steps:

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/tuner/lr_finder.py:481, in _try_loop_run(trainer, params)
    479 loop.load_state_dict(deepcopy(params["loop_state_dict"]))
    480 loop.restarting = False
--> 481 loop.run()

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py:199, in Loop.run(self, *args, **kwargs)
    197 try:
    198     self.on_advance_start(*args, **kwargs)
--> 199     self.advance(*args, **kwargs)
    200     self.on_advance_end()
    201     self._restarting = False

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py:267, in FitLoop.advance(self)
    265 self._data_fetcher.setup(dataloader, batch_to_device=batch_to_device)
    266 with self.trainer.profiler.profile("run_training_epoch"):
--> 267     self._outputs = self.epoch_loop.run(self._data_fetcher)

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py:199, in Loop.run(self, *args, **kwargs)
    197 try:
    198     self.on_advance_start(*args, **kwargs)
--> 199     self.advance(*args, **kwargs)
    200     self.on_advance_end()
    201     self._restarting = False

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py:213, in TrainingEpochLoop.advance(self, data_fetcher)
    210     self.batch_progress.increment_started()
    212     with self.trainer.profiler.profile("run_training_batch"):
--> 213         batch_output = self.batch_loop.run(kwargs)
    215 self.batch_progress.increment_processed()
    217 # update non-plateau LR schedulers
    218 # update epoch-interval ones only when we are at the end of training epoch

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py:199, in Loop.run(self, *args, **kwargs)
    197 try:
    198     self.on_advance_start(*args, **kwargs)
--> 199     self.advance(*args, **kwargs)
    200     self.on_advance_end()
    201     self._restarting = False

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py:90, in TrainingBatchLoop.advance(self, kwargs)
     88     outputs = self.optimizer_loop.run(optimizers, kwargs)
     89 else:
---> 90     outputs = self.manual_loop.run(kwargs)
     91 if outputs:
     92     # automatic: can be empty if all optimizers skip their batches
     93     # manual: #9052 added support for raising `StopIteration` in the `training_step`. If that happens,
     94     # then `advance` doesn't finish and an empty dict is returned
     95     self._outputs.append(outputs)

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py:199, in Loop.run(self, *args, **kwargs)
    197 try:
    198     self.on_advance_start(*args, **kwargs)
--> 199     self.advance(*args, **kwargs)
    200     self.on_advance_end()
    201     self._restarting = False

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/manual_loop.py:110, in ManualOptimization.advance(self, kwargs)
    107 kwargs = self._build_kwargs(kwargs, self._hiddens)
    109 # manually capture logged metrics
--> 110 training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
    111 del kwargs  # release the batch from memory
    112 self.trainer.strategy.post_training_step()

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:1494, in Trainer._call_strategy_hook(self, hook_name, *args, **kwargs)
   1491     return
   1493 with self.profiler.profile(f"[Strategy]{self.strategy.__class__.__name__}.{hook_name}"):
-> 1494     output = fn(*args, **kwargs)
   1496 # restore current_fx when nested context
   1497 pl_module._current_fx_name = prev_fx_name

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py:378, in Strategy.training_step(self, *args, **kwargs)
    376 with self.precision_plugin.train_step_context():
    377     assert isinstance(self.model, TrainingStep)
--> 378     return self.model.training_step(*args, **kwargs)

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/neuralprophet/time_net.py:756, in TimeNet.training_step(self, batch, batch_idx)
    754 self.train_epoch_prediction = predicted
    755 # Calculate loss
--> 756 loss, reg_loss = self.loss_func(inputs, predicted, targets)
    758 # Optimization
    759 optimizer = self.optimizers()

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/neuralprophet/time_net.py:739, in TimeNet.loss_func(self, inputs, predicted, targets)
    737     steps_per_epoch = math.ceil(self.trainer.estimated_stepping_batches / self.trainer.max_epochs)
    738     progress_in_epoch = 1 - ((steps_per_epoch * (self.current_epoch + 1) - self.global_step) / steps_per_epoch)
--> 739     loss, reg_loss = self._add_batch_regularizations(loss, self.current_epoch, progress_in_epoch)
    740 else:
    741     reg_loss = torch.tensor(0.0, device=self.device)

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/neuralprophet/time_net.py:900, in TimeNet._add_batch_regularizations(self, loss, epoch, progress)
    898 l_season = self.config_seasonality.reg_lambda
    899 if self.seasonality.season_dims is not None and l_season is not None and l_season > 0:
--> 900     for name in self.season_params.keys():
    901         reg_season = utils.reg_func_season(self.season_params[name])
    902         reg_loss += l_season * reg_season

File ~/.local/share/virtualenvs/ml_prophet-8L5JPCp0/lib/python3.9/site-packages/torch/nn/modules/module.py:1269, in Module.__getattr__(self, name)
   1267     if name in modules:
   1268         return modules[name]
-> 1269 raise AttributeError("'{}' object has no attribute '{}'".format(
   1270     type(self).__name__, name))

AttributeError: 'TimeNet' object has no attribute 'season_params'
```

**Environement (please complete the following information):**

 - Python 3.9
 - NeuralProphet version 0.5.2 [PYPI with `pip install neuralprophet`]

Not sure if this is to be expected?

**Comment by Lejboelle** [comment]
Sorry, just noticed this has been fixed in 0.5.3, thank you.
I can confirm it is working after upgrading to 0.5.3.

Closing issue.
